### ISSUE TITLE
ApiException: (404) Reason: Not Found

### ISSUE THREAD

**Issue by pathikg** [JovianML/opendatasets#6]
I am using Google Colab where I am downloading this dataset : https://www.kaggle.com/datasets/hereisburak/pins-face-recognition 
using opendatasets library

I've uploaded my kaggle.json into the files section of Google Colab as well but when I am doing `od.download(url)` I am getting following error :

![image](https://user-images.githubusercontent.com/55437218/160253230-bf56cd37-41c9-4f42-bcd8-08e76d93aab5.png)

I always do this same process but this time it is not working
So what could be the reason and how to resolve it ?

versions : 
Python : 3.7.13
opendatasets : 0.1.20

**Comment by BirajCoder** [comment]
Just remove the `datasets/` from the link. 

Example:
Not Working: "https://www.kaggle.com/datasets/maricinnamon/batman-films"
Working: "https://www.kaggle.com/maricinnamon/batman-films"
